### ISSUE TITLE
Clean up runs and logs 

### ISSUE THREAD

**Issue by odemakov** [odemakov/scriptflow#3]
Add project/task config to clean up policy. For example for project we can set "delete logs older than 30 days" but for particular task we can overwrite that policy.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add clean up policy fields to project and task models, and implement a function to remove outdated logs based on the configuration.

You can review changes in this commit: https://github.com/mnmnk43434/odemakov-script-flow-3/commit/1fca422161fc745e78e3f88ed56a2f73c765855c.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
